#!/usr/bin/env bash

task=$1

cat << --- >> $task.c
/*
ID: xerxes.1
LANG: C
TASK: $task
*/

#include <stdio.h>
#include <stdlib.h>
#include <string.h>

int main() {
    FILE *fin  = fopen("$task.in", "r");
    FILE *fout = fopen("$task.out", "w");

    return 0;
}
---
